name: hate-detection
channels:
  - pytorch
  - xformers
  - nvidia
  - conda-forge
  - nodefaults
dependencies:
  - accelerate=0.26.*
  - bitsandbytes=0.42.*
  - cuda-nvcc
  - datasets=2.16.*
  - einops=0.7.*
  - fire
  - flask
  - matplotlib>=3.7
  - peewee
  - peft=0.7.*
  - pip
  - python=3.10
  - pytorch=2.1.*
  - pytorch-cuda=11.8
  - scikit-learn>=1.3
  - torchvision=0.16.*
  - transformers=4.37.*
  - tqdm
  - wandb
  - xformers=0.0.*
  # dev
  - black
  - isort
  - ipykernel
  - pre-commit
  - pip:
      - flash-attn==2.5.*
      - trl==0.7.*
      - unsloth[conda] @ git+https://github.com/unslothai/unsloth.git
